[kafka]
#host = "192.168.0.132:9092"
host = "120.78.95.66:9092"
groupId = "plumelog"

[elastic]
url = "http://192.168.0.132:9200"
username = ""
password = ""
keepDays = 3
# 定制日志级别不存储到ES
logLevels = "DEBUG"
[gin]
port = 8090
username = "admin"
password = "admin"
expireTime = 10080